# Generated by Django 2.2.3 on 2019-07-05 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='view',
            name='description',
            field=models.TextField(max_length=2000, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='view',
            name='name_view',
            field=models.CharField(max_length=100, null=True, verbose_name='Название в классе'),
        ),
        migrations.AlterField(
            model_name='view',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название в меню'),
        ),
    ]
