# Generated by Django 2.2.3 on 2019-07-05 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0002_auto_20190705_0855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='view',
            name='description',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='Описание'),
        ),
    ]
