# Generated by Django 2.2.3 on 2019-07-09 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0004_auto_20190705_0915'),
    ]

    operations = [
        migrations.CreateModel(
            name='Error',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('description', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Описание')),
                ('attachment', models.ImageField(blank=True, upload_to='error/attachment', verbose_name='вложение')),
                ('view', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wiki.View')),
            ],
        ),
    ]
