# Generated by Django 2.2.3 on 2019-07-25 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0006_error_decision'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelRooms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.IntegerField()),
                ('hotel_id', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
        ),
    ]
