# Generated by Django 2.2.3 on 2019-08-27 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0007_hotelrooms'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HotelRooms',
        ),
    ]
