# Generated by Django 2.2.3 on 2019-08-30 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0008_delete_hotelrooms'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Error',
            new_name='Knowledge',
        ),
    ]
