# Generated by Django 2.2.3 on 2019-09-03 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0010_module_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledge',
            name='attachment',
            field=models.ImageField(blank=True, upload_to='static/error/attachment', verbose_name='вложение'),
        ),
    ]
