# Generated by Django 2.2.3 on 2019-09-03 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0011_auto_20190903_0711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledge',
            name='attachment',
            field=models.ImageField(blank=True, upload_to='knowledge/attachment', verbose_name='вложение'),
        ),
    ]
