# Generated by Django 2.2.3 on 2019-09-03 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0012_auto_20190903_0742'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='knowledge',
            name='attachment',
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('attachment', models.ImageField(blank=True, upload_to='knowledge/attachment', verbose_name='вложение')),
                ('knowledge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wiki.Knowledge')),
            ],
        ),
    ]
