# Generated by Django 2.2.3 on 2019-09-03 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0013_auto_20190903_2050'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attachment',
            old_name='attachment',
            new_name='path',
        ),
    ]
