# Generated by Django 2.2.3 on 2019-10-05 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0015_auto_20191005_1037'),
    ]

    operations = [
        migrations.RenameField(
            model_name='knowledge',
            old_name='number',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='attachment',
            name='knowledge',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wiki.Knowledge', to_field='id'),
        ),
    ]
