# Generated by Django 2.2.3 on 2019-10-07 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0016_auto_20191005_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledge',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
